etcd:
  image: quay.io/coreos/etcd:v2.3.3
  net: host
  command: >
    -listen-client-urls http://0.0.0.0:4040
    -advertise-client-urls http://127.0.0.1:4040
    -listen-peer-urls http://127.0.0.1:4041
