calico-node:
  image: calico/node:latest
  container_name: calico-node
  net: host
  privileged: true
  restart: always
  environment:
  - HOSTNAME=k8s_host
  - IP= 
  - IP6= 
  - CALICO_NETWORKING=true 
  - AS= 
  - NO_DEFAULT_POOLS= 
  - ETCD_AUTHORITY=127.0.0.1:4040
  - ETCD_SCHEME=http 
  volumes:
  - /var/run/calico:/var/run/calico:rw
  - /var/log/calico:/var/log/calico:rw
